#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
PARENT_DIR="$(dirname "$ROOT_DIR")"
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $ROOT_DIR

source "$ROOT_DIR/functions.sh"

export ROOT_DIR

export -f print_info
export -f print_success

ask_for_sudo

while true; do
  ask_for_confirmation "Warning: This shell will overwrite your current workspace setup. Proceed?"
  case $REPLY in
    [Yy]* ) break;;
    [Nn]* ) exit;;
    * ) echo "Please answer, yes or no"
  esac
done

print_info "Running shells..."

for SHELL in $ROOT_DIR/shells/*
do
  print_info "Running $(basename $SHELL)..."
  sh $SHELL
done

exec zsh
